### ISSUE TITLE
World Generation - Stone Layer Generation

### ISSUE THREAD

**Issue by Muddykat-tech** [Immersive-Geology-Team/Immersive-Geology#10]
Stone Layer Generation
============

**Completion Requirements**
A script that is able to generate a modifiable amount of different stone layers that supports biome changes and layer type requests. 
Example layer functions to think about:
~~~java
StoneLayerGen.addGlobalLayer(Layer, layer); // add a new layer that is applied to all biomes
StoneLayerGen.addLayerExclude(Layer layer, Biome biome); //adds a layer to everywhere except the biome specified.
StoneLayerGen.addLayer(Layer layer, Biome biome);
StoneLayerGen.getLayerType(int checkHeight, Biome currentBiome);
~~~

**Code Recommendations**
Separate Class Type for 'Layer'
Layers generate based on the number of layers added in, for example:
~~~java
StoneLayerGen.addGlobalLayer(stonelayer1);
StoneLayerGen.addGlobalLayer(stonelayer2);
~~~
The world will generate with the top half of the world as **stonelayer1** and the bottom half as **stonelayer2**.
If you add in a third layer after that, **stonelayer2** becomes the middle layer and **stonelayer3** the bottom layer.

**Comment by NightmareTwilight** [comment]
Maybe add thickness to layers, as an optional input.
