### ISSUE TITLE
Internal server error when picking up items - (Mahou Tsukai incompatibility)

### ISSUE THREAD

**Issue by SSampyla** [Immersive-Geology-Team/Immersive-Geology#102]
Hello,

I found an interesting bug when Mahou Tsukai is installed with Immersive Geology. On a server, all players get internal server error when picking up any immersive geology items. No other mods installed besides IE. Deleting player data fixes this until IG item is picked up again. No issues in singleplayer or Mahou Tsukai items.

Forge 36.2.35
immersive_geology-beta_v1.1-1.16.5.jar
mahoutsukai-1.16.5-v1.34.16.jar

**Comment by muddykat-tech** [comment]
We'll keep an eye on this issue, hopefully the next update fixes it.

Otherwise we'll look into a patch for it.
