### ISSUE TITLE
I've translated it into Chinese

### ISSUE THREAD

**Issue by CyberKanjousen** [Immersive-Geology-Team/Immersive-Geology#106]
I've translated your mod into Chinese. Although it's not translated well, could you add it into your mod next release? Thanks!
 http://mcpack.dwbrss.xyz/dwb/zh_cn.zip

**Comment by muddykat-tech** [comment]
Thanks for the hard work!

Once we're about to release we'll add it in!

**Comment by CyberKanjousen** [comment]
Not at all. dwb
