### ISSUE TITLE
sheet metal not working for immersive engineering machines 

### ISSUE THREAD

**Issue by archmichaeliii** [Immersive-Geology-Team/Immersive-Geology#130]
the iron sheetmetal from immersive geology is overwriting the iron sheet metal from immersive engineering and will not let you complete multiblock machines tested with silo and tank. confirmed they built when built with spawned immersive engineering iron Sheetmetal with creative mode.

**Comment by NightmareTwilight** [comment]
We don’t create duplicates anymore.
