### ISSUE TITLE
Fixed up Bauxite Processing Chain to not impede IE

### ISSUE THREAD

**Issue by muddykat-tech** [Immersive-Geology-Team/Immersive-Geology#131]
Stuff to be done:
 - Return IE ore Block when requested getBlock(BlockPattern.oreblock)
 - Introduce cutting with proper I/O

**Comment by UnSchtalch** [comment]
>Return IE ore Block when requested getBlock(BlockPattern.oreblock)

Do we really need this? Like I have not seen any use of it.
