### ISSUE TITLE
[1.16.5Server]Immersive Geology (immersive_geology) has failed to load correctly

### ISSUE THREAD

**Issue by OcrSu** [Immersive-Geology-Team/Immersive-Geology#145]
[crash-2022-08-15_09.13.40-fml.txt](https://github.com/Immersive-Geology-Team/Immersive-Geology/files/9334521/crash-2022-08-15_09.13.40-fml.txt)
Java11

**Comment by UnSchtalch** [comment]
Thank you for feedback!

Muddy, something wrong with our init routine on dedicated servers. We're trying to call for client proxy here, donnoe why. 

ImmersiveGeology.java, line 87.

**Comment by muddykat-tech** [comment]
I'll make a quick hot patch for this.

**Comment by UnSchtalch** [comment]
Fixed, testing myself at dedicated server setup

**Comment by UnSchtalch** [comment]
Fixed in f66a41cf06e63fc6e8d8cb29a3540950b91e486c
Need to fix animation now.

**Comment by UnSchtalch** [comment]
Fixed in IG 1.4-beta
