### ISSUE TITLE
Kaolinite QoL

### ISSUE THREAD

**Issue by UnSchtalch** [Immersive-Geology-Team/Immersive-Geology#147]
1) Set tool for Kaolinite to be shovel
2) Add recipe of basic (!) smelting kaolinite clay to refractory brick
3) Increase default spawn frequency twice, allow it to replace dirt (if not)

**Comment by Olexi** [comment]
Also please check animation for Block of Kaolinite when breaking it. Most of blocks have "breaking" texture, while this has none.
