### ISSUE TITLE
Missing chemical recipe for Aluminium Compound Dust

### ISSUE THREAD

**Issue by Olexi** [Immersive-Geology-Team/Immersive-Geology#153]
Also missing some recipes from Chemical Vat... Maybe these errors are connected.

**Comment by Olexi** [comment]
It's JEI bug, @UnSchtalch saw reproduced error.

**Comment by UnSchtalch** [comment]
Issue is connected to drawing GUI screen for said recipes.
Gonna fix tomorrow.

**Comment by UnSchtalch** [comment]
Fixed in 4131447f725b2fb5bdab11f6ae209bdf445537c3
