### ISSUE TITLE
Compatibility with other immersive addons and like Engineers Décor with some recipe with the Bloomery

### ISSUE THREAD

**Issue by ShadowkingREEEE** [Immersive-Geology-Team/Immersive-Geology#162]
lost account mad another one Lol but yes found some problems with it

**Comment by UnSchtalch** [comment]
Had discussion in Discord.
OP wanted to have some compat with ED, like to be able to smelt some native ores in the electric furnace.
Probably better to leave this to datapack
@Muddykat-tech your opinion?

**Comment by muddykat-tech** [comment]
Hmm, I'll look into native compatibility first and if it's a massive hassle I won't otherwise I'll see about getting it implemented
