### ISSUE TITLE
Crash and Error.s

### ISSUE THREAD

**Issue by Shadowblitz16** [Immersive-Geology-Team/Immersive-Geology#167]
### Minecraft Version

1.20.1

### Immersive Geology Version

v0.2.1-b4-mc1.20.1

### Expected Behavior

No errors, No crash.

### Actual Behavior

Lots of errors and a crash.

### Steps to reproduce

1. Install the mods in the log.
2. Run minecraft.

### Debug Crash Log

https://pastebin.com/4zSkaxGK

**Comment by muddykat-tech** [comment]
The error was caused because you didn't install Immersive engineering.

Immersive geology requires immersive engineering; This crash was caused as immersive geology was unable to find a required dependent class from immersive engineering.
