### ISSUE TITLE
Request for progress update on github release

### ISSUE THREAD

**Issue by creepebucket** [Immersive-Geology-Team/Immersive-Geology#171]
### Explain your idea

Thanks to the contributors for their work on Immersive Geology! As a fan of the project, I'd like to be kept up to date on the current status of the mod development. Would it be possible to show us the compiled .jar files of the mods in a github release? I understand that there is a delay in releasing mods on platforms such as modrinth.

**Comment by muddykat-tech** [comment]
Sure, I can implement this feature.
