### ISSUE TITLE
Tags for wires should be "forge:wires/material". Currently "forge:wire/material"

### ISSUE THREAD

**Issue by ElRichiRicon** [Immersive-Geology-Team/Immersive-Geology#172]
### Minecraft Version

1.20.1

### Immersive Geology Version

0.2.3-b10

### Expected Behavior

Most other mods use `forge:wires/material`, so this mod should use them too.

### Actual Behavior

Wires added by this mod have `forge:wire/material`. Singular. Probably a typo.
This makes the wires unusable for other mods.

I didn't see any recipes with this tag,

### Steps to reproduce

1. Install the mod
2. Check the items added
3. See the tags

### Debug Crash Log

No crash

**Comment by muddykat-tech** [comment]
I've confirmed the issue, and noted it as a bug.

This will be patched in version 0.3.1
