### ISSUE TITLE
The amount of memory required skyrocketed

### ISSUE THREAD

**Issue by xiaojuzi122** [Immersive-Geology-Team/Immersive-Geology#173]
### Minecraft Version

1.20.1

### Immersive Geology Version

0.3.0

### Expected Behavior

The mod should not require up to 8GB of RAM

### Actual Behavior

However, the latest (0.3.0) needs more than that, which seriously affects the gameplay experience

### Steps to reproduce

I switched to 0.2.3-b10 and the memory usage was normal, but after I updated 0.3.0, the memory usage was up to 10G
I'm a little skeptical that each block has a tag ...
![77d4ef6f7704f1d50babaf209ab6a384](https://github.com/user-attachments/assets/547876b6-ccaf-4877-8d2e-047878c2df73)

### Debug Crash Log

Not yet

**Comment by muddykat-tech** [comment]
Thank you for reporting this issue. I've verified that this is unintended behavior and it is indeed of critical importance.

As a token of appreciation for your contribution, and as part of our Bug Bounty Program, you are eligible to choose one of the following rewards:
- A custom painting type
- A custom armor trim
- A custom banner type

Feel free to reach out to me via the Engineering Department Discord Server or email me at muddykat@proton.me to claim your reward or if you have any further questions.
