### ISSUE TITLE
Item/Block registry rework

### ISSUE THREAD

**Issue by Pabilo8** [Immersive-Geology-Team/Immersive-Geology#33]
Because of the complications with the new tags system, a need to use tile entities to store material data and general hassle with the items, the way we register things should be changed.

TODO:
 - [x] Clean up the existing code
-  [ ] ~~Add an event for other mods to register materials~~
 - [x] Change the items to register in the old way (using only ids, like immersivegeology:ingot_copper)
 - [x] Add a custom model loader for mass loading of the item models
 - [x] Add a custom blockstate loader for mass loading of the blockstates

Optional:
 - [ ] Add an ability to specify a custom texture / model for the material

**Comment by NightmareTwilight** [comment]
Better to use BlockStates than TileEntities, could otherwise cause lag.
