### ISSUE TITLE
Modular Tool

### ISSUE THREAD

**Issue by NightmareTwilight** [Immersive-Geology-Team/Immersive-Geology#46]
Adding a modular tool + crafting.
Change tool-type based on the head: Pickaxe, Axe, Shovel, and Hammer.
Will replace vanilla and IE versions.
Obligatory parts: Handle, Binding, and Head.
Optional Part(s): Tip.

**Comment by muddykat-tech** [comment]
Better to have interrogation with other mods like Tetra or Tinker's Construct
