### ISSUE TITLE
Gravity Seperator Crash [Ticking block entity]

### ISSUE THREAD

**Issue by Royal-Jelly** [Immersive-Geology-Team/Immersive-Geology#88]
Gravity Separator does not appear to like the IE capacitor placed on the on the input for water, or any of the other inputs.

Here is a link to the whole crash on:
[PasteBin](https://pastebin.com/za0WtPjt)

Sorry ahead of time, I like finding bugs

**Comment by muddykat-tech** [comment]
Cool, thanks for bringing this to our attention!

I'll see about getting this fixed.

**Comment by muddykat-tech** [comment]
Fixed
