### ISSUE TITLE
Engineer's Manual cant open

### ISSUE THREAD

**Issue by Scarfiremmi** [Immersive-Geology-Team/Immersive-Geology#90]
When you try to open the Engineer's Manual, it gives a missing entry error (according to Discord it is Unobtania
[latest.log](https://github.com/Immersive-Geology-Team/Immersive-Geology/files/7796852/latest.log)
)

**Comment by muddykat-tech** [comment]
Will be fixed in the next update, in about 15 minutes.

@NightmareTwilight was a bit to eager to upload the latest build and forgot to add the manual entry.

**Comment by muddykat-tech** [comment]
Fixed in latest Release
