### ISSUE TITLE
CRASH with Roadrunner

### ISSUE THREAD

**Issue by Cynix32** [Immersive-Geology-Team/Immersive-Geology#91]
Crash at startup with these mods installed. I have tested it in a clean setup with the details below
MC 1.6.5
Forge 36.2.22
RoadRunner-mc1.16.5-1.4.0.jar
ImmersiveEngineering-1.16.5-5.0.7-143.jar
immersive_geology-1.0v5.jar
Crashlog: https://pastebin.com/QEvD4BJN

**Comment by muddykat-tech** [comment]
Looking into what I can do with fixing it

**Comment by UnSchtalch** [comment]
Can you elaborate precisely, how did you got this crash?

**Comment by Vapaman** [comment]
Getting the same crash on startup, Roadrunner installed.

**Comment by Cynix32** [comment]
@UnSchtalch This crash can be reproduced by simply using the mods stated. The game won't start and just straight up crash.

**Comment by malte0811** [comment]
Also happens without RoadRunner. Not at startup, but e.g. when placing Uranium Sheetmetal Stairs from the creative menu: https://gist.github.com/malte0811/e05c6e757414e90536606638c4ed1eaf

**Comment by muddykat-tech** [comment]
Bump up the priority, I'll be looking into this further.

**Comment by UnSchtalch** [comment]
> Also happens without RoadRunner. Not at startup, but e.g. when placing Uranium Sheetmetal Stairs from the creative menu: https://gist.github.com/malte0811/e05c6e757414e90536606638c4ed1eaf

Wait. 
Uranium sheetmetal stairs. In IG 1.0v6? 

Looks like we've broken datagen here, they should not exist, according to code.

**Comment by malte0811** [comment]
I think you may be missing an override for `hasStairs` in `MaterialMetalUranium`. The `hasPlate` override stops the recipe from being generated, but the block still exists and is present in the creative menu.

**Comment by muddykat-tech** [comment]
Fixed and yeah, you were correct @malte0811, it was the missing override!
