### ISSUE TITLE
Implement support for Tinkers Contruct tools

### ISSUE THREAD

**Issue by JadianRadiator** [Immersive-Geology-Team/Immersive-Geology#95]
Immersive Geology ore currently doesn't drop anything when mined with a Tinkers Construct tool of the level required (or higher) for the ore in question.

**Comment by muddykat-tech** [comment]
Noted, will address this when possible.

**Comment by muddykat-tech** [comment]
This has been resolved now with the beta 1.1 update!
Thanks for reporting this issue!
