### ISSUE TITLE
Mekanism Compat

### ISSUE THREAD

**Issue by 1mphuls3** [Immersive-Geology-Team/Immersive-Geology#96]
It would be nice to see compatibility for Mekanism ore processing (Clean and Dirty Slurries, Clumps, Shards, and Dirty Dust/Grit), as well as Osmium ore stuff. Sorry if that's a lot to ask!

**Comment by muddykat-tech** [comment]
I love Mekanism and I would like to add some measure of compatibility, but Immersive Geology and Mekansim have a very different process when it comes to getting more ingots out of an ore block, IG gives you a lot of an item, which is then slowly lost over time if processed with inefficient methods.

Whereas Mekanism starts you with one item and slowly you accumulate more.

Essentially, I'd need to think very carefully about how we'd implement a method of compatibility, but it isn't off the table. 

For now however, we have a lot to do and this isn't our focus, perhaps we'll come back to this another time.
