### ISSUE TITLE
Crash while starting a server

### ISSUE THREAD

**Issue by emanuele246gi** [Immersive-Geology-Team/Immersive-Geology#97]
Immersive Geology beta_v1.1 for Minecraft 1.16.5, on Forge 36.2.33

Crash Report: https://pastebin.com/B0fTAQ7B

**Comment by UnSchtalch** [comment]
Thanks for posting an issue.

Bug is well-known. Just try to start server once more, it's blinking behaviour

**Comment by emanuele246gi** [comment]
Yep I did it, I just wanted to report it
